<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_INGRESAR</name>
   <tag></tag>
   <elementGuidId>3a4d9046-e0e9-4c11-ba90-c7caa878670e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.w-100.mat-raised-button.mat-primary.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0427a95d-90c3-4ed4-8954-ce82c297924c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 mat-raised-button mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>6e017313-7add-424e-ae96-42e84fbdec81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>3864f7b8-1b6f-43e5-bcc0-7c31ce55513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c1037ecb-c479-47c2-b23a-35e791f9ee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>43cf8457-bfc9-4e8e-8d3c-84ae264a8fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INGRESAR</value>
      <webElementGuid>271c8b8f-088f-4235-9059-3b7b26b24b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranslate&quot;]/body[@class=&quot;bg-main material-app&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;nx-login&quot;]/div[@class=&quot;contenido&quot;]/div[@class=&quot;row row-content&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;content-left&quot;]/div[@class=&quot;animated fadeIn ng-star-inserted&quot;]/form[@class=&quot;example-form p-20 col-xs-10 col-sm-8 col-md-12 col-lg-10 col-xl-7 ng-dirty ng-touched ng-valid&quot;]/button[@class=&quot;w-100 mat-raised-button mat-primary cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>8d9bd7f5-9afc-492d-b8fe-5ccd593e376e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>59133f73-a4e7-4b20-a97f-4f325b49e71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>7e9266b1-0f09-4d90-b8d3-9a56a5def715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'INGRESAR' or . = 'INGRESAR')]</value>
      <webElementGuid>74fb6517-dd74-4b89-b317-aba77dec235e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
