<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-user-circle font-size-40 color-2</name>
   <tag></tag>
   <elementGuidId>0b5f5be7-688a-43c9-83c9-45cf9d18e8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-user-circle.font-size-40.color-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>38aec4d5-333f-48f0-a97a-964bc19af528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user-circle font-size-40 color-2</value>
      <webElementGuid>4bf8a921-6aa8-440b-8dfe-faca10a3e6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranslate&quot;]/body[@class=&quot;bg-main material-app&quot;]/app-root[1]/app-appmain[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;material-app bg-main&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/mat-toolbar[@class=&quot;mat-elevation-z2 index-2 bg-light sticky top-0 z-index-2 px-0 mat-toolbar mat-toolbar-multiple-rows&quot;]/mat-toolbar-row[@class=&quot;d-flex justify-content-between p-0 px-md-3 mat-toolbar-row&quot;]/div[@class=&quot;w-100 d-flex align-items-center justify-content-between ng-star-inserted&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/a[1]/i[@class=&quot;fa fa-user-circle font-size-40 color-2&quot;]</value>
      <webElementGuid>d3c186bb-48ce-456b-80a8-371b6ee80139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>c2ed72c2-14a1-43aa-8e28-e5ee9894ad82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
