<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-power-off mr-2</name>
   <tag></tag>
   <elementGuidId>d6b1b6dd-9497-4f2b-a6d8-985e167c275e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/div/div/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-power-off.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>310bce8e-154f-4fbe-a720-fccdb23944f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-power-off mr-2</value>
      <webElementGuid>6d3562f3-285a-4527-9cfd-5fb3076e9984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/div[@class=&quot;mat-menu-panel ng-trigger ng-trigger-transformMenu ng-tns-c15-4 mt-40 ng-star-inserted mat-elevation-z2 mat-menu-before mat-menu-below&quot;]/div[@class=&quot;mat-menu-content&quot;]/button[@class=&quot;h-initial line-height-initial p-2 font-size-13 mat-menu-item cdk-focused cdk-mouse-focused&quot;]/i[@class=&quot;fa fa-power-off mr-2&quot;]</value>
      <webElementGuid>370263d2-9888-4522-9f1e-8fdfaa3e3820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/div/div/button[2]/i</value>
      <webElementGuid>95a91aa5-6998-4842-bdc0-008248fef527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>79309a54-b815-4a33-a401-2b4a240385d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
