<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_INGRESAR</name>
   <tag></tag>
   <elementGuidId>182a5b10-eb7a-4911-9cc0-2acf2dd393c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.w-100.mat-raised-button.mat-primary.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25cf18a6-ec8b-4d27-81bf-3777b732b661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>32e8df2d-0689-498e-b91c-54e76a18d533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INGRESAR</value>
      <webElementGuid>f1b716cc-2b3c-451c-b66d-cbdef91bb030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranslate&quot;]/body[@class=&quot;bg-main material-app&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;nx-login&quot;]/div[@class=&quot;contenido&quot;]/div[@class=&quot;row row-content&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;content-left&quot;]/div[@class=&quot;animated fadeIn ng-star-inserted&quot;]/form[@class=&quot;example-form p-20 col-xs-10 col-sm-8 col-md-12 col-lg-10 col-xl-7 ng-dirty ng-touched ng-valid&quot;]/button[@class=&quot;w-100 mat-raised-button mat-primary cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>ec33a13b-60b5-4b9f-99a3-96ac7dfd9eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>e5fe6d76-c123-4c85-898e-3bdf2db66136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'INGRESAR' or . = 'INGRESAR')]</value>
      <webElementGuid>dee95f7b-35c4-421e-8a1c-a9f4e3c45bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
