<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cerrar Sesin</name>
   <tag></tag>
   <elementGuidId>439407d6-ebd9-40b2-8cd5-3a1dd84dd29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-logout/div/mat-dialog-actions/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-raised-button.mat-warn.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>138d5654-d728-4cd3-b2c7-49845cbd8c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>2af21499-5c9a-49e4-9e13-f82f3cb19ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerrar Sesión</value>
      <webElementGuid>2f0981a2-f19e-4837-9908-365274185b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-logout[@class=&quot;ng-star-inserted&quot;]/div[1]/mat-dialog-actions[@class=&quot;mat-dialog-actions&quot;]/div[@class=&quot;w-100&quot;]/button[@class=&quot;mat-raised-button mat-warn cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>22d883f3-8f35-4ce3-9232-fc98e7121dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-logout/div/mat-dialog-actions/div/button[2]/span</value>
      <webElementGuid>87539774-8289-4c7c-a7d5-09726664370f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/div/button[2]/span</value>
      <webElementGuid>2a0a080c-90fb-4278-af92-498d3367eb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cerrar Sesión' or . = 'Cerrar Sesión')]</value>
      <webElementGuid>eaee56de-ea10-4ba3-873c-6f5b51fe51f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
