<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_INGRESAR</name>
   <tag></tag>
   <elementGuidId>182a5b10-eb7a-4911-9cc0-2acf2dd393c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.w-100.mat-raised-button.mat-primary.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43a9f9b8-e0d9-47f3-b313-ff563f726fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>9bd08a96-1434-49af-a498-8a5bacdfee95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INGRESAR</value>
      <webElementGuid>533b5c10-0916-4d82-ae81-8d6956603a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranslate&quot;]/body[@class=&quot;bg-main material-app&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;nx-login&quot;]/div[@class=&quot;contenido&quot;]/div[@class=&quot;row row-content&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;content-left&quot;]/div[@class=&quot;animated fadeIn ng-star-inserted&quot;]/form[@class=&quot;example-form p-20 col-xs-10 col-sm-8 col-md-12 col-lg-10 col-xl-7 ng-dirty ng-touched ng-valid&quot;]/button[@class=&quot;w-100 mat-raised-button mat-primary cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>35fbc7cb-ab16-4722-9202-1638881961f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>b384f954-598c-4a45-a999-87b693069898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'INGRESAR' or . = 'INGRESAR')]</value>
      <webElementGuid>22a7a66a-da38-4327-a52a-7cfb13e8dbb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
